enum ScreenNameEnum {
  //Auth Screens
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  LOGIN_OPTION = 'LOGIN_OPTION',
  SIGNUP_SCREEN = 'SIGNUP_SCREEN',
  PASSWORDRESET_OPTION = 'PASSWORDRESET_OPTION',
 CREATE_PASSWORD = 'CREATE_PASSWORD',
  OTP_SCREEN = 'OTP_SCREEN',
  ASK_LOCATION ='ASK_LOCATION',
  LOCATION_SCREEN ='LOCATION_SCREEN',
  //TAb
  BOTTOM_TAB ='BOTTOM_TAB',
  PROFILE_SCREEN='PROFILE_SCREEN',
  GROUP_CODE='GROUP_CODE',
  CREATE_NEWPASS= 'CREATE_NEWPASS',
  TEAM_SCREEN ='TEAM_SCREEN',
 
  CHAT_SCREEN ='CHAT_SCREEN',
  CHAT_CONTACT_SCREEN ='CHAT_CONTACT_SCREEN',
  
  HOME_ROUTE='HOME_ROUTE',
  HOME_SCREEN ='HOME_SCREEN',
  NOTIFICATION_SCREEN ='NOTIFICATION_SCREEN',



  CHANGE_PASSWORD ='CHANGE_PASSWORD',

  NOTIFICAION_SETTING ='NOTIFICAION_SETTING',
  STEP_ONE ='STEP_ONE',
  STEP_TWO ='STEP_TWO',
  SELECT_ROLE ='SELECT_ROLE',
  STEP_FOUR ='STEP_FOUR',
  SOCIAL_LOGIN ='SOCIAL_LOGIN',
  CREATE_CONNECTION='CREATE_CONNECTION',
  CALENDAR_SCREEN ='CALENDAR_SCREEN',
  MORE_SCREEN = 'MORE_SCREEN',

  // PROFILE SECTION
  PRIVACY_POLICY ='PRIVACY_POLICY',
  MY_PROFILE ='MY_PROFILE',
  WALL_SCREEN = 'WALL_SCREEN',
  REGISTRATION_SCREEN ='REGISTRATION_SCREEN',
  CHILD_PROFILE ='CHILD_PROFILE',
  MY_CHILDREN ='MY_CHILDREN',
  SUPPORT_SCREEN ='SUPPORT_SCREEN',
  VIDEO_SCREEN = 'VIDEO_SCREEN'
  


  

  
}

export default ScreenNameEnum;
