enum ScreenNameEnum {
  //Auth Screens
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  LOGIN_OPTION = 'LOGIN_OPTION',
  SIGNUP_SCREEN = 'SIGNUP_SCREEN',
  PASSWORDRESET_OPTION = 'PASSWORDRESET_OPTION',
 CREATE_PASSWORD = 'CREATE_PASSWORD',
  OTP_SCREEN = 'OTP_SCREEN',
  ASK_LOCATION ='ASK_LOCATION',
  LOCATION_SCREEN ='LOCATION_SCREEN',
  SIGNIN_OPTION = 'SIGNIN_OPTION',
  CHILD_DETAILS ='CHILD_DETAILS',
  SENT_CONNECTIONREQ ='SENT_CONNECTIONREQ',
  ASKCREATEALOGIN='ASKCREATEALOGIN',
  CREATECHILDACCOUNT ='CREATECHILDACCOUNT',
  WELCOME_SCREEN ='WELCOME_SCREEN',
  CHILDCREATEACCOUNTLOGIN='CHILDCREATEACCOUNTLOGIN',
  COACH_STEP1 ='COACH_STEP1',
  PLAYER_STEP1 = 'PLAYER_STEP1',
  NOWITHOUTSCREEN = 'NOWITHOUTSCREEN',
  REQUESTSENTSETP2 = 'REQUESTSENTSETP2',
  FIRST_TIMECHILD ='FIRST_TIMECHILD',
  coachWall='coachWall',
  cocheEvent ='cocheEvent',
  cocheVideo = 'cocheVideo',
  coachProfile ='coachProfile',
  PersnalInfo ='PersnalInfo',

  //TAb
  BOTTOM_TAB ='BOTTOM_TAB',
  PROFILE_SCREEN='PROFILE_SCREEN',
  GROUP_CODE='GROUP_CODE',
  CREATE_NEWPASS= 'CREATE_NEWPASS',
  TEAM_SCREEN ='TEAM_SCREEN',
 
  CHAT_SCREEN ='CHAT_SCREEN',
  CHAT_CONTACT_SCREEN ='CHAT_CONTACT_SCREEN',
  
  HOME_ROUTE='HOME_ROUTE',
  HOME_SCREEN ='HOME_SCREEN',
  NOTIFICATION_SCREEN ='NOTIFICATION_SCREEN',



  CHANGE_PASSWORD ='CHANGE_PASSWORD',

  NOTIFICAION_SETTING ='NOTIFICAION_SETTING',
  GROUP_DETAILS ='GROUP_DETAILS',
  USER_DETAILS ='USER_DETAILS',
  SELECT_ROLE ='SELECT_ROLE',
  CONTINUE_USERDETAILS ='CONTINUE_USERDETAILS',
  SOCIAL_LOGIN ='SOCIAL_LOGIN',
  CREATE_OR_REQUESTCONNECTION='CREATE_OR_REQUESTCONNECTION',
  CALENDAR_SCREEN ='CALENDAR_SCREEN',
  MORE_SCREEN = 'MORE_SCREEN',

  // PROFILE SECTION
  PRIVACY_POLICY ='PRIVACY_POLICY',
  MY_PROFILE ='MY_PROFILE',
  WALL_SCREEN = 'WALL_SCREEN',
  REGISTRATION_SCREEN ='REGISTRATION_SCREEN',
  CHILD_PROFILE ='CHILD_PROFILE',
  MY_CHILDREN ='MY_CHILDREN',
  SUPPORT_SCREEN ='SUPPORT_SCREEN',
  VIDEO_SCREEN = 'VIDEO_SCREEN'
  


  

  
}

export default ScreenNameEnum;
